SELECT 
        gender,
        email,
        phone,
        cell,
        "name.title" as title,
        "name.first" as first_name,
        "name.last" as last_name,
        "location.street.number" as street_number,
        "location.street.name" as street_name,
        "location.city" as city,
        "location.state" as state,
        "location.country" as country,
        "location.postcode" as postcode,
        "location.coordinates.latitude" as latitude,
        "location.coordinates.longitude" as longitude,
        "location.timezone.offset" as offset,
        "location.timezone.description" as "description",
        "login.uuid" as uuid,
        "login.username" as username,
        "login.password" as password,
        "login.salt" as salt,
        "login.md5" as md5,
        "login.sha1" as sha1,
        "login.sha256" as sha256,
        "dob.date" as date_of_birth,
        "dob.age" as age,
        "registered.date" as registered_date,
        "id.name" as id_name,
        "id.value" as id_value,
        "picture.large" as large_picture,
        "picture.medium" as medium_picture,
        "picture.thumbnail" as thumbnail_picture
FROM {{ source('source', 'users') }}


